### ISSUE TITLE
Release T248

### ISSUE THREAD

**Issue by RezinoviyDed** [scarburato/hid-tminit#12]
Hello.
The steering wheel T248 went on sale. I bought it, but ffb is missing on linux. Can I help you with something? Perhaps I can provide some data about the steering wheel from the logs.

**Comment by scarburato** [comment]
Post the `lsusb` output

Anyway this module is only to initialize wheels that report themself as `Thrustmaster FFB Wheel` not to implement ffb support

**Comment by Draluy** [comment]
HI, here is the lsusb. Im interested in T248 support also :)

Bus 003 Device 002: ID 044f:b696 ThrustMaster, Inc. Thrustmaster Racing Wheel FFB

**Comment by scarburato** [comment]
It does not seems that it needs any further initialization... You have to try if the id (`b696` in this case) changes after the windows driver has been loaded

**Comment by Draluy** [comment]
@RezinoviyDed Please check this project: https://github.com/Kimplul/hid-tmff2

After installing the driver, I was able to use the t248 wit FFB on Assetto Corsa Competizione. No Luck with Automobilista 2 yet.

**Comment by scarburato** [comment]
Oh I see, so the T248 definitively does not need any further initialization. Closing for now
