### ISSUE TITLE
T80 ferrari 488 gtb edition

### ISSUE THREAD

**Issue by skankerror** [scarburato/hid-tminit#3]
Hi guys, I have a thrustmaster t80 and it's not working on linux, only buttons are recognized, the axes don't move.
I installed tm driver on a windows PC, and capture usb packets. I don't know if this capture is ok...

[thrustmaster.pcap.txt](https://github.com/scarburato/hid-tminit/files/5724286/thrustmaster.pcap.txt)
[lsusb.txt](https://github.com/scarburato/hid-tminit/files/5724287/lsusb.txt)

**Comment by skankerror** [comment]
https://drive.google.com/file/d/10DDzhgadoCipWhA7UxtP_XYbBsMWi59X/view?usp=sharing

Here's a link for pcap not in txt version...

**Comment by scarburato** [comment]
Unfortunately it doesn't seem that your wheel uses the initialization method provided by this driver (or any kind initialization at all) as it appears directly to the machine as a `Thrustmaster T80` (idProduct is 0xb668) instead `Thrustmaster FFB Wheel` (with id 0xb65d). 

To confirm this you can plug the wheel on your Linux machine and run `lsusb -vvv -d044f:` (colon included). 

If it is not a `Thrustmaster FFB Wheel` then this driver is not what are you looking for. If it is a `Thrustmaster T80` and the controls are not mapped properly then it is a problem with HID, maybe you can try to fix with jscal

**Comment by skankerror** [comment]
[lsusb-vvv-d044f.txt](https://github.com/scarburato/hid-tminit/files/5726173/lsusb-vvv-d044f.txt)

Here's output of lsusb -vvv -d044f:

Unforunately jscal -c /dev/input/js* doesn't work cos axis values are always the same, they never move

Even with a cat /dev/input/js1 wheel and pedals do nothing, only buttons are showing activities.

**Comment by scarburato** [comment]
> idProduct          0xb668 

Ok, this is out of scope for this driver as the T80 seems to be already initialized when it's plugged so I'm gonna close this issue. 

Probably the wheel has a broken hid descriptor, I am not sure if it is necessary to write a specific hid driver or you can fix from userspace. Maybe you can find useful [this article](https://flameeyes.blog/2017/04/24/elecom-deft-and-the-broken-descriptor/)

**Comment by skankerror** [comment]
thanks, I'll try something this way
