### ISSUE TITLE
TS-XW support?

### ISSUE THREAD

**Issue by simon50keda** [scarburato/hid-tminit#7]
Hi,
is there any chance support can be extended for TS-XW and TS-PC models?

Here is lsusb output:
[lsusb_tsxw.txt](https://github.com/scarburato/hid-tminit/files/6655636/lsusb_tsxw.txt)

**Comment by scarburato** [comment]
``` iProduct                2 Thrustmaster TS-XW Racer GIP Wheel```

The wheel seems to be already initialized. It does not seems that other actions are necessary

**Comment by simon50keda** [comment]
Hm, but it's not listed as a device inside the jstest-gtk, how come?

**Comment by scarburato** [comment]
No idea. Maybe it's not a hid device so it needs a specific driver  (typical hid device shows something like `bInterfaceClass         3 Human Interface Device`). If you attach the wheel on Windows with the correct driver does it appear with a different idProduct? If not then it's out of scope for this driver
