### ISSUE TITLE
TMX Pro doesn't work

### ISSUE THREAD

**Issue by BFCE** [scarburato/hid-tminit#8]
cloned, make, make install, tried manually loading module using insmod, no reaction from wheel at all, no results on evtest

```Bus 001 Device 008: ID 044f:b67e ThrustMaster, Inc. Thrustmaster TMX GIP Racing Wheel

Couldn't open device, some information will be missing

Device Descriptor:

  bLength                18

  bDescriptorType         1

  bcdUSB               2.00

  bDeviceClass          255 Vendor Specific Class

  bDeviceSubClass       255 Vendor Specific Subclass

  bDeviceProtocol       255 Vendor Specific Protocol

  bMaxPacketSize0        64

  idVendor           0x044f ThrustMaster, Inc.

  idProduct          0xb67e 

  bcdDevice            1.01

  iManufacturer           1 Thrustmaster

  iProduct                2 Thrustmaster TMX GIP Racing Wheel

  iSerial                 3 0000C1CF6721E555

  bNumConfigurations      1

```

**Comment by scarburato** [comment]
Can you post the output of `dmesg` when plugging the device?

**Comment by BFCE** [comment]
> Can you post the output of `dmesg` when plugging the device?

[12744.311654] usb 1-3: new full-speed USB device number 7 using xhci_hcd
[12744.627435] usb 1-3: New USB device found, idVendor=044f, idProduct=b67e, bcdDevice= 1.01
[12744.627447] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[12744.627452] usb 1-3: Product: Thrustmaster TMX GIP Racing Wheel
[12744.627455] usb 1-3: Manufacturer: Thrustmaster
[12744.627459] usb 1-3: SerialNumber: 0000C1CF6721E555
bfce@pop-os:~/hid-tminit$

**Comment by BFCE** [comment]
As far as the readme states, the wheel is supposed to show up as a generic thrustmaster product. But mine shows up as "Thrustmaster TMX GIP Racing Wheel". I bought this wheel only a couple months ago and it has the latest firmware version. Maybe this behavior was changed by thrustmaster along the way? 

If needed i'd be willing to setup a usb packet capture. This wheel is the only thing i still need to boot windows for.

**Comment by scarburato** [comment]
The aim of this driver is to initialize, if necessary, a `Thrustmaster FFB Wheel` and make it appear to the system as the "real" wheel and not to provide any further support for input or ffb. 

If necessary another driver has to be implemented.

I suspect it is necessary to send a specific usb packet to wheel when the input device is open like for the [t150](https://github.com/scarburato/t150_driver/blob/a47b1bcb0e8aeee9af8acd36ee83aee923ecd82b/hid-t150/input.c#L55) and the [t300](https://github.com/Kimplul/hid-tmff2/blob/f1e563479f9e3015aa3f4b3e989b0b9bf9abc34f/hid-tmt300rs.c#L1303)
